EmmaWorkManagementProject/EmmaWorkManagementProject/Models/UserProfileViewModel.cs
namespace EmmaWorkManagementProject.Models
{
    public class UserProfileViewModel
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Surname { get; set; }
        public string? About { get; set; }
        public DateTime? Registered { get; set; }
        public string? Email { get; set; }
        public IFormFile? Avatar { get; set; }
        public byte[]? Image { get; set; }
    }
}

EmmaWorkManagementProject/EmmaWorkManagementProject/Controllers/UserProfileController.cs
using AutoMapper;
using EmmaWorkManagement.BusinessLayer.Dtos;
using EmmaWorkManagement.BusinessLayer.Interfaces;
using EmmaWorkManagement.BusinessLayer.Services.UserTasks;
using EmmaWorkManagement.Data;
using EmmaWorkManagement.Entities;
using EmmaWorkManagement.Exceptions;
using EmmaWorkManagementProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.IO;

namespace EmmaWorkManagementProject.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IUserProfileService _profileService;
        private readonly IMapper _mapper;

        public UserProfileController(IAccountService accountService, IUserProfileService userProfileService, IMapper mapper)
        {
            _accountService = accountService;
            _profileService = userProfileService;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> GetUserProfile()
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (accountDto is null)
                {
                    throw new ObjectNotFoundException("Account");
                }
                var accountId = accountDto.Id;
                var activeProfile = await _profileService.GetUserProfile(accountId);

                return View(new UserProfileViewModel()
                {
                    Id = activeProfile.Id,
                    Name = activeProfile.Name,
                    Surname = activeProfile.Surname,
                    About = activeProfile.About,
                    Email = activeProfile.Email,
                    Registered = activeProfile.Registered,
                    Image = activeProfile.Avatar
                });
            }
            catch (ObjectNotFoundException notFoundException)
            {
                return RedirectToAction("Error", notFoundException);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> GetUserProfile(UserProfileViewModel profile)
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (accountDto is null)
                {
                    throw new ObjectNotFoundException(profile.Name);
                }

                var activeAccountId = accountDto.Id;
                var activeProfile = await _profileService.GetUserProfile(activeAccountId);
                activeProfile.About = profile.About;

                await _profileService.UpdateUserProfile(activeProfile);

                return RedirectToAction("GetUserProfile");
            }
            catch (ObjectNotFoundException notFoundException)
            {
                return RedirectToAction("Error", notFoundException);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAccountName()
        {
            return View();
        }

        public async Task<IActionResult> UpdateAccountName(UserProfileViewModel model)
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (accountDto is null)
                {
                    throw new ObjectNotFoundException(model.Name);
                }

                var activeAccountId = accountDto.Id;
                var profileDto = await _profileService.GetUserProfile(activeAccountId);
                profileDto.Name = model.Name;
                profileDto.Surname = model.Surname;
                accountDto.Name = model.Name;
                accountDto.Surname = model.Surname;

                await _accountService.UpdateAccountName(accountDto);
                await _profileService.UpdateUserProfile(profileDto);

                return RedirectToAction("GetUserProfile");
            }
            catch (ObjectNotFoundException notFoundException)
            {
                return RedirectToAction("Error", notFoundException);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateAccountEmail()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateAccountEmail(UserProfileViewModel model)
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (accountDto is null)
                {
                    throw new ObjectNotFoundException(model.Name);
                }

                var activeAccountId = accountDto.Id;
                var profileDto = await _profileService.GetUserProfile(activeAccountId);
                profileDto.Email = model.Email;
                accountDto.Email = model.Email;

                await _accountService.UpdateAccountName(accountDto);
                await _profileService.UpdateUserProfile(profileDto);

                return RedirectToAction("GetUserProfile");
            }
            catch (ObjectNotFoundException notFoundException)
            {
                return RedirectToAction("Error", notFoundException);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", ex);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProfileAvatar()
        {
            return PartialView("UpdateProfileAvatar");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfileAvatar(UserProfileViewModel model)
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            var profileDto = await _profileService.GetUserProfile(accountDto.Id);

            if (model.Avatar is not null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(model.Avatar.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)model.Avatar.Length);
                }
                profileDto.Avatar = imageData;
            }

            await _accountService.UpdateAccount(profileDto);

            return RedirectToAction("GetUserProfile", "UserProfile");
        }
    }
}

EmmaWorkManagementProject/EmmaWorkManagementProject/Controllers/UserTaskController.cs
using EmmaWorkManagement.BusinessLayer.Dtos;
using EmmaWorkManagement.BusinessLayer.Interfaces;
using EmmaWorkManagement.Data;
using EmmaWorkManagement.Data.Interaces;
using EmmaWorkManagement.Data.Interfaces;
using EmmaWorkManagement.Entities;
using EmmaWorkManagement.Exceptions;
using EmmaWorkManagementProject.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EmmaWorkManagementProject.Controllers
{
    public class UserTaskController : Controller
    {
        private readonly IUserTaskService _userTaskService;
        private readonly IAccountService _accountService;

        public UserTaskController(IUserTaskService userTaskService, IAccountService accountService, ApplicationDbContext applicationDbContext)
        {
            _userTaskService = userTaskService;
            _accountService = accountService;
        }

        public async Task<IActionResult> GetSortedUserTasksByPriority()
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }
                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetSortedUserTasksByPriority(activeAccountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetTodayUserTasks()
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if(activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }
                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetTodayUserTasksAsync(activeAccountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetImportantUserTasks()
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }

                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetImportantUserTasksAsync(activeAccountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetUpcomingUserTasks()
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }

                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetUpcomingUserTasksAsync(activeAccountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetOverdueUserTasks()
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }

                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetOverdueUserTasksAsync(activeAccountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetUserTasksByName()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetUserTasksByName(string name)
        {
            var activeAccountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if (activeAccountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }

                var activeAccountId = activeAccountDto.Id;
                var response = await _userTaskService.GetUserTasksByNameAsync(activeAccountId, name);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (ObjectNotFoundException objNotFound)
            {
                return RedirectToAction("Error");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetCompletedTasks()
        {
            var accountDto = await _accountService.GetAccountByEmailAsync(User.Identity.Name);
            try
            {
                if(accountDto == null)
                {
                    throw new ObjectNotFoundException("Account");
                }

                var accountId = accountDto.Id;
                var response = await _userTaskService.GetCompletedTasksAsync(accountId);
                var result = response.Select(q => new UserTaskViewModel
                {
                    Id = q.Id,
                    Name = q.Name,
                    Summary = q.Summary,
                    DateOfCreation = q.DateOfCreation,
                    DateOfCompletion = q.DateOfCompletion,
                    Priority = q.Priority,
                }).ToArray();

                return View(result);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error");
            }
        }

        public async Task<IActionResult> GetUserTask(int id, bool isJson)
        {
            try
            {
                var userTaskDto = await _userTaskService.GetUserTask(id);
                if (userTaskDto == null)
                {
                    throw new ObjectNotFoundException("Task");
                }

                var response = new UserTaskViewModel()
                {
                    Id = userTaskDto.Id,
                    Name = userTaskDto.Name,
                    Summary = userTaskDto.Summary,
                    DateOfCreation = userTaskDto.DateOfCreation,
                    DateOfCompletion = userTaskDto.DateOfCompletion,

EmmaWorkManagementProject/EmmaWorkManagementProject/Views/UserProfile/GetUserProfile.cshtml
@model UserProfileViewModel

<link rel="stylesheet" href="~/css/AccountStyles.css" asp-append-version="true" />

<section style="height: 100%;">
    <div class="row g-0">
        <div class="col-md-3 gradient-custom text-center text-white sidebar">
            <header>
                <div class="container sidebarSettings">
                    <h1 class="header_sidebar__text">Settings</h1>
                </div>
            </header>
            <div class="sidebar_container">
                <ul class="sidebar_container__content list-group">
                    <a asp-controller="Account" asp-action="UpdatePassword" class="content_list__active list_item action_link">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="action_image bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                        Account
                    </a>
                    <a asp-controller="Account" asp-action="UpdatePassword" class="content_list list_item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="action_image bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                        Account
                    </a>
                    <a asp-controller="Account" asp-action="UpdatePassword" class="content_list list_item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="action_image bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z" />
                        </svg>
                        Account
                    </a>
                </ul>
            </div>
        </div>
        <div class="col-md-9 main_content">
            <form role="form" method="post">
                <header>
                    <div class="container sidebarAccount">
                        <div class="sidebarAccount_text">
                            <h1 class="header_sidebar__text">Account</h1>
                        </div>
                        <div class="sidebarAccount_button">
                            <a class="navbarAddAction text-light" asp-controller="UserTask" asp-action="GetTodayUserTasks">
                                <svg xmlns="http://www.w3.org/2000/svg" style="color: #333;" width="20" height="20" fill="currentColor" class="navbarAddActionImage bi bi-plus-lg" viewBox="0 0 16 16">
                                    <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z" />
                                </svg>
                            </a>
                        </div>
                    </div>
                </header>
                <div class="main_content_container">
                    <hr class="container_line">
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">Registered</h3>
                        <div class="button_action">
                            @Model.Registered
                        </div>
                    </div>
                    <hr class="container_line">
                    <div class="content_image_info_container">
                        <h3 class="image_info_text">Photo</h3>
                        <div class="image_info_container">
                            <div class="image_photo_container">
                                @if(Model.Image != null)
                                {
                                    <img style='width:80px; height:80px; border-radius: 3rem;' src="data:image/jpeg;base64,@(Convert.ToBase64String(Model.Image))" />
                                }
                                else
                                {
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp" alt="Avatar" style="width: 80px;" />
                                }
                            </div>
                            <div class="image_button_container">
                                <div class="upper"></div>
                                <div class="button_action">
                                    <button type="button" class="btn btn-light getInfoAction image_upload_button" onclick="openModal({url: '/UserProfile/UpdateProfileAvatar', data: '@Model.Id'})" data-toggle="ajax-modal" data-target="Modal">
                                        Upload photo
                                    </button>
                                </div>
                                <div class="button_laber_text">Pick your new photo up</div>
                            </div>
                        </div>
                    </div>
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">Name</h3>
                        <div>@Model.Name @Model.Surname</div>
                        <div class="button_action">
                            <button type="button" class="btn btn-light getInfoAction image_upload_button" onclick="openModal({url: '/UserProfile/UpdateAccountName', data: '@Model.Id'})" data-toggle="ajax-modal" data-target="Modal">
                                Change name
                            </button>
                        </div>
                    </div>
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">About</h3>
                        <textarea asp-for="About" class="form-control" type="text">@Model.About</textarea>
                        <button class="btn btn-light image_upload_button" style="margin-top: .5rem;" type="submit">
                            <span class="upload_action">Change about</span>
                        </button>
                    </div>
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">Email</h3>
                        <div>@Model.Email</div>
                        <div class="button_action">
                            <button class="btn btn-light image_upload_button">
                                <a class="upload_action" asp-area="" asp-controller="UserProfile" asp-action="UpdateAccountEmail">Change email</a>
                            </button>
                        </div>
                    </div>
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">Password</h3>
                        <div class="button_action">
                            <button class="btn btn-light image_upload_button">
                                <a class="upload_action" asp-area="" asp-controller="Account" asp-action="UpdatePassword">Change password</a>
                            </button>
                        </div>
                    </div>
                    <hr class="container_line">
                    <div class="content_name_info_container">
                        <h3 class="image_info_text">Delete account</h3>
                        <div class="delete_account__text">This will immediately delete all of your data including tasks, projects, comments, and more. This can’t be undone.</div>
                        <div class="button_action">
                            <button class="btn btn-light image_upload_button">
                                <a class="upload_action text-danger" asp-area="" asp-controller="Account" asp-action="Delete">Delete account</a>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

@*<div class="card-body p-4">
    <h6>Information</h6>
    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
         alt="Avatar" class="img-fluid my-5" style="width: 80px;" />
    <hr class="mt-0 mb-4">
    <div class="row pt-1">
        <div class="col-6 mb-3">
            <h6>Email</h6>
            <p class="text-muted">@Model.Email</p>
            <button type="button" class="deleteButton_button btn btn-outline-danger">
                <a asp-controller="Account" asp-action="UpdatePassword">
                    Change password
                </a>
            </button>
        </div>
        <div class="col-6 mb-3">
            <h6>Registered</h6>
            <p class="text-muted">@Model.Registered</p>
        </div>
    </div>
    <h6>Account</h6>
    <hr class="mt-0 mb-4">
    <div class="row pt-1">
        <div class="col-6 mb-3">
            <h6>Change password</h6>
            <p class="text-muted"><a></a></p>
        </div>
    </div>
    <div class="row pt-1">
        <div class="col-6 mb-3">
            <h6>Update info:</h6>
            <form role="form" method="post">
                <div class="form-group">
                    <label>Your name</label>
                    <input asp-for="Name" class="form-control" type="text" placeholder="Enter your name">
                </div>
                <div class="form-group">
                    <label>Your surname</label>
                    <input asp-for="Surname" class="form-control" type="text" placeholder="Enter your surname">
                </div>
                <div class="form-group">
                    <label>About information</label>
                    <textarea asp-for="About" class="form-control" type="text"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" data-original-title="" title="">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>*@

EmmaWorkManagementProject/EmmaWorkManagementProject/Views/UserProfile/UpdateAccountEmail.cshtml
@model UserProfileViewModel

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>


<div class="container" id="perevod" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="card">
                <div class="card-body">
                    <h4 class="py-10 text-center">Enter task information: </h4>
                    <form asp-action="UpdateAccountName" method="post">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label" asp-for="Email">Enter your new email</label>
                            <div class="col-sm-8">
                                <input asp-for="Email" class="form-control" type="text">
                            </div>
                        </div>
                        <input type="submit" value="Submit" class="btn">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<script>document.getElementById('davaToday').valueAsDate = new Date();</script>

EmmaWorkManagementProject/EmmaWorkManagementProject/Views/UserProfile/UpdateAccountName.cshtml
@model UserProfileViewModel

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>


<div class="container" id="perevod" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="card">
                <div class="card-body">
                    <h4 class="py-10 text-center">Enter task information: </h4>
                    <form asp-action="UpdateAccountName" method="post">
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label" asp-for="Name">Enter your name</label>
                            <div class="col-sm-8">
                                <input asp-for="Name" class="form-control" type="text">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-4 col-form-label" asp-for="Surname">Enter your surname</label>
                            <div class="col-sm-8">
                                <input asp-for="Surname" class="form-control" type="text">
                            </div>
                        </div>
                        <input type="submit" value="Submit" class="btn">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<script>document.getElementById('davaToday').valueAsDate = new Date();</script>