EmmaWorkManagementProject/EmmaWorkManagementProject/Models/SubtaskViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EmmaWorkManagementProject.Models
{
    public class SubtaskViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [MinLength(1, ErrorMessage = "Name should have more than 1 symbol")]
        [MaxLength(50, ErrorMessage = "Name should have less than 50 symbols")]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [MaxLength(1000, ErrorMessage = "Name should have less than 1000 symbols")]
        [Display(Name = "Comment")]
        public string? Comment { get; set; }

        public int UserTaskId { get; set; }
    }
}

EmmaWorkManagementProject/EmmaWorkManagementProject/Controllers/SubtaskController.cs
using EmmaWorkManagement.BusinessLayer.Dtos;
using EmmaWorkManagement.BusinessLayer.Interfaces;
using EmmaWorkManagement.BusinessLayer.Services.Accounts;
using EmmaWorkManagement.Data;
using EmmaWorkManagement.Entities.Entities;
using EmmaWorkManagement.Exceptions;
using EmmaWorkManagementProject.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmmaWorkManagementProject.Controllers
{
    public class SubtaskController : Controller
    {
        private readonly ISubtaskService _subtaskService;
        private readonly IUserTaskService _userTaskService;
        private readonly ApplicationDbContext _applicationDbContext;

        public SubtaskController(ISubtaskService subtaskService, IUserTaskService userTaskService, ApplicationDbContext applicationDbContext)
        {
            _subtaskService = subtaskService;
            _userTaskService = userTaskService;
            _applicationDbContext = applicationDbContext;
        }

        public async Task DeleteSubtask(int id)
        {
            await _subtaskService.DeleteSubtask(id);
            RedirectToAction("GetTodayUserTasks", "UserTask");
        }

        [HttpGet]
        public async Task<IActionResult> CreateSubtask(int id, bool isJson)
        {
            try
            {
                var userTask = await _userTaskService.GetUserTask(id);
                var model = new SubtaskViewModel()
                {
                    UserTaskId = userTask.Id
                };

                return PartialView(model);
            }
            catch(Exception ex)
            {
                throw;
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateSubtask(SubtaskViewModel model)
        {
            var userTaskDto = await _userTaskService.GetUserTask(model.UserTaskId);
            try
            {
                if(userTaskDto is null)
                {
                    throw new ObjectNotFoundException("UserTask");
                }
                var userTaskId = userTaskDto.Id;
                var subtaskDto = new SubtaskDto()
                {
                    Name = model.Name,
                    Comment = model.Comment,
                    UserTaskId = model.UserTaskId
                };

                await _subtaskService.CreateSubtask(subtaskDto, userTaskId);

                return RedirectToAction("GetTodayUserTasks", "UserTask");
            }
            catch (ObjectNotFoundException ex)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> UpdateSubtask(int id)
        {
            var subtaskDto = await _subtaskService.GetSubtask(id);
            var model = new SubtaskViewModel()
            {
                Name = subtaskDto.Name,
                Comment = subtaskDto.Comment,
                Id = id,
                UserTaskId = subtaskDto.UserTaskId
            };

            return PartialView(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSubtask(SubtaskViewModel model)
        {
            var subtaskDto = new SubtaskDto()
            {
                Id = model.Id,
                UserTaskId = model.UserTaskId,
                Name = model.Name,
                Comment = model.Comment
            };

            await _subtaskService.UpdateSubtask(subtaskDto);

            return RedirectToAction("GetTodayUserTasks", "UserTask");
        }

        public async Task CompleteSubtask(int id)
        {
            try
            {
                await _subtaskService.CompleteSubtask(id);
            }
            catch (Exception ex)
            {
                RedirectToAction("Error");
            }
        }
    }
}

EmmaWorkManagementProject/EmmaWorkManagementProject/Views/Subtask/CreateSubtask.cshtml
@model SubtaskViewModel

@{
    ViewData["Title"] = "Important";
}

<h4 class="py-10 text-center">Enter task information: </h4>
<form asp-action="CreateSubtask" asp-controller="Subtask" asp-route-UserTaskId="@Model.UserTaskId" class="addForm" method="post">
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Name:</label>
        <div class="col-sm-8">
            <input asp-for="Name" class="form-control" type="text">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label" asp-for="Comment"></label>
        <div class="col-sm-8">
            <textarea asp-for="Comment" class="form-control" type="text"></textarea>
        </div>
    </div>
    <div class="form-group row">
        <input type="submit" value="Add subtask" class="btn text-danger submitAddBtn">
    </div>
</form>

EmmaWorkManagementProject/EmmaWorkManagementProject/Views/Subtask/UpdateSubtask.cshtml
@model SubtaskViewModel

<h4 class="py-10 text-center">Edit subtask information: </h4>
<form asp-action="UpdateSubtask" asp-controller="Subtask" asp-route-id="@Model.Id" class="addForm" method="post">
    <div class="form-group row">
        <label class="col-sm-4 col-form-label">Name:</label>
        <div class="col-sm-8">
            <input asp-for="Name" class="form-control" type="text" value="@Model.Name">
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-4 col-form-label" asp-for="Comment"></label>
        <div class="col-sm-8">
            <textarea asp-for="Comment" class="form-control" type="text">@Model.Comment</textarea>
        </div>
    </div>
    <div class="form-group row">
        <input type="submit" value="Update" class="btn text-danger submitAddBtn">
    </div>
</form>